apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # You can replace this with your own Docker image
          ports:
            - containerPort: 80  # Expose port 80 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port the container is listening on
  type: LoadBalancer  # You can change this to ClusterIP or NodePort depending on your needs
